import assert from "node:assert/strict";
import { APPLICATION_STORAGE_KEYS, clearApplicationLocalData, readApplicationStorage, storageUserMessage, writeApplicationStorage } from "./local-profile-data";
assert.deepEqual(APPLICATION_STORAGE_KEYS, ["companyData", "projectsData", "profileStructure", "generatedProfile", "authoredFamilyDecision", "exportDecision"]);
assert.equal(new Set(APPLICATION_STORAGE_KEYS).size, APPLICATION_STORAGE_KEYS.length);
const values = new Map<string,string>([["unrelated-app", "keep"], ...APPLICATION_STORAGE_KEYS.map((key) => [key, `value:${key}`] as [string,string])]);
const storage = { getItem: (key: string) => values.get(key) ?? null, removeItem: (key: string) => { values.delete(key); } };
const result = clearApplicationLocalData(storage as Pick<Storage,"getItem"|"removeItem">);
assert(result.complete); assert.equal(result.removedKeys.length, APPLICATION_STORAGE_KEYS.length); assert.equal(values.get("unrelated-app"), "keep"); assert(APPLICATION_STORAGE_KEYS.every((key) => !values.has(key)));
const again = clearApplicationLocalData(storage as Pick<Storage,"getItem"|"removeItem">); assert(again.complete && again.removedKeys.length === 0);
const writes = new Map<string, string>();
assert(writeApplicationStorage({ setItem: (key, value) => writes.set(key, value) }, "companyData", "{}").ok);
assert.equal(readApplicationStorage({ getItem: (key) => writes.get(key) ?? null }, "companyData"), "{}");
const quota = writeApplicationStorage({ setItem: () => { const error = new Error("full"); Object.assign(error, { name: "QuotaExceededError" }); throw error; } }, "projectsData", "{}");
assert(!quota.ok && quota.code === "storage_quota" && storageUserMessage(quota.code).includes("storage is full"));
console.log("Application-owned local data cleanup and unrelated-origin isolation tests passed.");
