import { jsPDF } from "jspdf";
import { createJsPDFMeasurementContext, evaluateContentEnvelope } from "./content-envelope";
import type { AuthoredPageTemplate, ContentEnvelope, ImageSlotValue, TemplateInstance } from "./types";
import { drawContainedOptionalLogo, preparedOptionalLogo } from "./packs/logo";

export type CoverTemplateId = `authored-cover-v1.${"editorial-warm" | "corporate-clean" | "dynamic-bold" | "architectural-modern" | "premium-dark" | "creative-soft"}`;
export type CoverPaletteId = "warm-neutral" | "navy-clean" | "charcoal-gold" | "blue-architectural" | "forest-premium" | "soft-lilac" | "tech-electric";
export type CoverStyleDescriptor = "modern" | "elegant" | "bold" | "technical" | "minimal" | "premium" | "creative";
export type CurrentFamilyId = "visual-portfolio" | "corporate-services" | "product-tech";

export type CoverPalette = Readonly<{ id: CoverPaletteId; background: readonly [number, number, number]; surface: readonly [number, number, number]; ink: readonly [number, number, number]; muted: readonly [number, number, number]; accent: readonly [number, number, number]; light: readonly [number, number, number] }>;
export const authoredCoverPalettes: readonly CoverPalette[] = [
  { id: "warm-neutral", background: [239, 232, 220], surface: [218, 202, 181], ink: [43, 39, 34], muted: [102, 92, 80], accent: [164, 112, 72], light: [250, 247, 241] },
  { id: "navy-clean", background: [247, 249, 251], surface: [221, 229, 237], ink: [17, 35, 57], muted: [80, 96, 115], accent: [38, 91, 145], light: [255, 255, 255] },
  { id: "charcoal-gold", background: [30, 31, 34], surface: [51, 52, 56], ink: [247, 243, 234], muted: [190, 184, 173], accent: [190, 145, 72], light: [255, 255, 255] },
  { id: "blue-architectural", background: [232, 239, 243], surface: [188, 207, 217], ink: [26, 48, 61], muted: [78, 104, 117], accent: [51, 111, 139], light: [250, 252, 253] },
  { id: "forest-premium", background: [24, 43, 37], surface: [42, 67, 57], ink: [244, 239, 226], muted: [185, 194, 181], accent: [181, 151, 91], light: [255, 253, 246] },
  { id: "soft-lilac", background: [245, 241, 248], surface: [223, 211, 232], ink: [59, 48, 66], muted: [111, 96, 119], accent: [139, 101, 151], light: [255, 255, 255] },
  { id: "tech-electric", background: [17, 24, 38], surface: [31, 45, 67], ink: [242, 247, 255], muted: [160, 177, 201], accent: [47, 203, 190], light: [255, 255, 255] },
] as const;

export type AuthoredCoverContent = { contentId: string; documentLabel: string; companyName: string; companyType: string; paletteId: CoverPaletteId; logo?: ImageSlotValue };
export type CoverSelectionFacts = { familyId: CurrentFamilyId; companyName: string; companyType?: string; industry?: string; styleDescriptor?: unknown; hasLogo: boolean };
export type CoverSelectionReason = { code: string; contribution: number };
export type CoverSelectionResult = { compatible: true; templateId: CoverTemplateId; paletteId: CoverPaletteId; normalizedStyle: CoverStyleDescriptor | null; rankings: readonly { templateId: CoverTemplateId; score: number; compatible: boolean; reasons: readonly CoverSelectionReason[] }[] } | { compatible: false; templateId: null; paletteId: null; normalizedStyle: CoverStyleDescriptor | null; rankings: readonly { templateId: CoverTemplateId; score: number; compatible: boolean; reasons: readonly CoverSelectionReason[] }[] };

type Definition = { id: CoverTemplateId; supportedFamilies: readonly CurrentFamilyId[]; styleTags: readonly CoverStyleDescriptor[]; toneTags: readonly string[]; compositionCategory: string; maxNameCharacters: number; supportsLogo: true; paletteIds: readonly CoverPaletteId[]; priority: number; font: "times" | "helvetica"; fontSize: number; nameWidth: number; nameLines: number; render: (pdf: jsPDF, instance: TemplateInstance<AuthoredCoverContent>, palette: CoverPalette, audit: Record<string, readonly string[]>) => void };
export type CoverTemplateDefinition = Definition;
const palette = (id: CoverPaletteId) => authoredCoverPalettes.find((entry) => entry.id === id) ?? authoredCoverPalettes[0];
const text = (instance: TemplateInstance<AuthoredCoverContent>, id: string) => { const slot = instance.preparedSlots[id]; if (!slot || slot.kind !== "text") throw new Error(`Prepared cover text ${id} unavailable.`); return slot.lines; };
const common = (pdf: jsPDF, instance: TemplateInstance<AuthoredCoverContent>, p: CoverPalette, audit: Record<string, readonly string[]>, name: { x: number; y: number; font: "times" | "helvetica"; size: number; color: readonly [number, number, number]; lineHeight?: number }, label: { x: number; y: number; color: readonly [number, number, number] }, type: { x: number; y: number; color: readonly [number, number, number] }, logoBox: { x: number; y: number; width: number; height: number }) => {
  drawContainedOptionalLogo(pdf, preparedOptionalLogo(instance), logoBox, p.light);
  const labelLines = text(instance, "documentLabel"); pdf.setTextColor(...label.color); pdf.setFont("helvetica", "bold"); pdf.setFontSize(7.5); pdf.setCharSpace(0.55); pdf.text([...labelLines], label.x, label.y); pdf.setCharSpace(0); audit.documentLabel = labelLines;
  const nameLines = text(instance, "companyName"); pdf.setTextColor(...name.color); pdf.setFont(name.font, "bold"); pdf.setFontSize(name.size); pdf.setLineHeightFactor(name.lineHeight ?? 0.98); pdf.text([...nameLines], name.x, name.y); audit.companyName = nameLines;
  const typeLines = text(instance, "companyType"); pdf.setTextColor(...type.color); pdf.setFont("helvetica", "normal"); pdf.setFontSize(9); pdf.setLineHeightFactor(1.35); pdf.text([...typeLines], type.x, type.y); audit.companyType = typeLines;
};

const definitions: readonly Definition[] = [
  { id: "authored-cover-v1.editorial-warm", supportedFamilies: ["visual-portfolio", "corporate-services"], styleTags: ["elegant", "modern", "premium"], toneTags: ["interior", "architecture", "hospitality", "design"], compositionCategory: "editorial-curve", maxNameCharacters: 48, supportsLogo: true, paletteIds: ["warm-neutral", "forest-premium"], priority: 100, font: "times", fontSize: 39, nameWidth: 105, nameLines: 3, render: (pdf, i, p, a) => { pdf.setFillColor(...p.background); pdf.rect(0, 0, 210, 297, "F"); pdf.setFillColor(...p.surface); pdf.ellipse(30, 255, 105, 92, "F"); pdf.setFillColor(...p.accent); pdf.ellipse(202, 18, 58, 52, "F"); pdf.setDrawColor(...p.accent); pdf.setLineWidth(0.8); pdf.line(112, 76, 184, 76); common(pdf, i, p, a, { x: 90, y: 127, font: "times", size: 39, color: p.ink }, { x: 112, y: 63, color: p.muted }, { x: 92, y: 190, color: p.muted }, { x: 141, y: 25, width: 43, height: 18 }); } },
  { id: "authored-cover-v1.corporate-clean", supportedFamilies: ["corporate-services", "visual-portfolio", "product-tech"], styleTags: ["minimal", "modern"], toneTags: ["consulting", "advisory", "legal", "accounting", "b2b"], compositionCategory: "corporate-column", maxNameCharacters: 72, supportsLogo: true, paletteIds: ["navy-clean", "blue-architectural"], priority: 95, font: "times", fontSize: 35, nameWidth: 118, nameLines: 4, render: (pdf, i, p, a) => { pdf.setFillColor(...p.background); pdf.rect(0, 0, 210, 297, "F"); pdf.setFillColor(...p.ink); pdf.rect(0, 0, 58, 297, "F"); pdf.setFillColor(...p.accent); pdf.rect(18, 28, 22, 2.2, "F"); pdf.setDrawColor(...p.surface); for (const y of [66, 112, 158, 204, 250]) pdf.line(58, y, 210, y); common(pdf, i, p, a, { x: 78, y: 111, font: "times", size: 35, color: p.ink }, { x: 18, y: 45, color: p.light }, { x: 79, y: 202, color: p.muted }, { x: 10, y: 71, width: 38, height: 24 }); } },
  { id: "authored-cover-v1.dynamic-bold", supportedFamilies: ["product-tech", "corporate-services"], styleTags: ["bold", "technical", "modern"], toneTags: ["technology", "software", "platform", "sales"], compositionCategory: "dynamic-diagonal", maxNameCharacters: 45, supportsLogo: true, paletteIds: ["tech-electric", "charcoal-gold"], priority: 98, font: "helvetica", fontSize: 38, nameWidth: 145, nameLines: 3, render: (pdf, i, p, a) => { pdf.setFillColor(...p.background); pdf.rect(0, 0, 210, 297, "F"); pdf.setFillColor(...p.surface); pdf.triangle(96, 0, 210, 0, 210, 148, "F"); pdf.setFillColor(...p.accent); pdf.triangle(0, 247, 0, 297, 74, 297, "F"); pdf.setDrawColor(...p.accent); pdf.setLineWidth(1.2); pdf.line(24, 67, 82, 67); common(pdf, i, p, a, { x: 24, y: 132, font: "helvetica", size: 38, color: p.ink }, { x: 24, y: 53, color: p.muted }, { x: 25, y: 202, color: p.muted }, { x: 145, y: 24, width: 45, height: 18 }); } },
  { id: "authored-cover-v1.architectural-modern", supportedFamilies: ["visual-portfolio", "corporate-services"], styleTags: ["modern", "technical", "minimal"], toneTags: ["architecture", "engineering", "construction", "real estate"], compositionCategory: "architectural-grid", maxNameCharacters: 60, supportsLogo: true, paletteIds: ["blue-architectural", "navy-clean"], priority: 92, font: "helvetica", fontSize: 33, nameWidth: 132, nameLines: 4, render: (pdf, i, p, a) => { pdf.setFillColor(...p.background); pdf.rect(0, 0, 210, 297, "F"); pdf.setDrawColor(...p.surface); pdf.setLineWidth(0.35); for (const x of [22, 70, 118, 166]) pdf.line(x, 0, x, 297); for (const y of [44, 98, 152, 206, 260]) pdf.line(0, y, 210, y); pdf.setFillColor(...p.accent); pdf.rect(0, 206, 70, 91, "F"); pdf.setFillColor(...p.ink); pdf.rect(166, 0, 44, 98, "F"); common(pdf, i, p, a, { x: 22, y: 123, font: "helvetica", size: 33, color: p.ink }, { x: 22, y: 31, color: p.muted }, { x: 94, y: 242, color: p.muted }, { x: 168, y: 18, width: 38, height: 18 }); } },
  { id: "authored-cover-v1.premium-dark", supportedFamilies: ["visual-portfolio", "corporate-services"], styleTags: ["premium", "elegant", "minimal"], toneTags: ["luxury", "premium", "boutique", "hospitality"], compositionCategory: "premium-frame", maxNameCharacters: 48, supportsLogo: true, paletteIds: ["forest-premium", "charcoal-gold"], priority: 90, font: "times", fontSize: 40, nameWidth: 137, nameLines: 3, render: (pdf, i, p, a) => { pdf.setFillColor(...p.background); pdf.rect(0, 0, 210, 297, "F"); pdf.setDrawColor(...p.accent); pdf.setLineWidth(0.6); pdf.rect(15, 15, 180, 267); pdf.setLineWidth(0.2); pdf.rect(20, 20, 170, 257); pdf.setFillColor(...p.accent); pdf.circle(105, 54, 2.2, "F"); common(pdf, i, p, a, { x: 36, y: 131, font: "times", size: 40, color: p.ink }, { x: 72, y: 77, color: p.muted }, { x: 52, y: 205, color: p.muted }, { x: 77, y: 35, width: 56, height: 16 }); } },
  { id: "authored-cover-v1.creative-soft", supportedFamilies: ["visual-portfolio", "product-tech"], styleTags: ["creative", "modern", "elegant"], toneTags: ["creative", "studio", "design", "lifestyle"], compositionCategory: "soft-orbits", maxNameCharacters: 60, supportsLogo: true, paletteIds: ["soft-lilac", "warm-neutral"], priority: 94, font: "times", fontSize: 36, nameWidth: 118, nameLines: 4, render: (pdf, i, p, a) => { pdf.setFillColor(...p.background); pdf.rect(0, 0, 210, 297, "F"); pdf.setFillColor(...p.surface); pdf.ellipse(188, 238, 88, 76, "F"); pdf.setDrawColor(...p.accent); pdf.setLineWidth(0.8); pdf.ellipse(24, 50, 52, 43); pdf.setLineWidth(0.3); pdf.ellipse(24, 50, 42, 34); pdf.setFillColor(...p.accent); pdf.circle(34, 236, 10, "F"); common(pdf, i, p, a, { x: 54, y: 127, font: "times", size: 36, color: p.ink }, { x: 54, y: 62, color: p.muted }, { x: 55, y: 204, color: p.muted }, { x: 142, y: 25, width: 44, height: 18 }); } },
] as const;

export const normalizeCoverStyleDescriptor = (value: unknown): CoverStyleDescriptor | null => typeof value === "string" && (["modern", "elegant", "bold", "technical", "minimal", "premium", "creative"] as const).includes(value.trim().toLowerCase() as CoverStyleDescriptor) ? value.trim().toLowerCase() as CoverStyleDescriptor : null;
const words = (facts: CoverSelectionFacts) => `${facts.companyType ?? ""} ${facts.industry ?? ""}`.toLowerCase();
export const selectAuthoredCover = (facts: CoverSelectionFacts): CoverSelectionResult => {
  const style = normalizeCoverStyleDescriptor(facts.styleDescriptor); const source = words(facts);
  const rankings = definitions.map((definition) => {
    const reasons: CoverSelectionReason[] = [];
    const compatible = definition.supportedFamilies.includes(facts.familyId) && facts.companyName.trim().length > 0 && facts.companyName.trim().length <= definition.maxNameCharacters;
    reasons.push({ code: definition.supportedFamilies.includes(facts.familyId) ? "family_supported" : "family_unsupported", contribution: definition.supportedFamilies.includes(facts.familyId) ? 4 : -100 });
    reasons.push({ code: facts.companyName.trim().length <= definition.maxNameCharacters ? "name_envelope_supported" : "name_envelope_exceeded", contribution: facts.companyName.trim().length <= definition.maxNameCharacters ? 2 : -100 });
    if (style) reasons.push({ code: definition.styleTags.includes(style) ? "style_match" : "style_neutral", contribution: definition.styleTags.includes(style) ? 3 : 0 });
    const tone = definition.toneTags.some((tag) => source.includes(tag)); reasons.push({ code: tone ? "company_tone_match" : "company_tone_neutral", contribution: tone ? 3 : 0 });
    reasons.push({ code: facts.hasLogo ? "optional_logo_supported" : "no_logo_supported", contribution: 1 });
    return { templateId: definition.id, score: reasons.reduce((sum, reason) => sum + reason.contribution, 0) + definition.priority / 1000, compatible, reasons };
  }).sort((a, b) => Number(b.compatible) - Number(a.compatible) || b.score - a.score || a.templateId.localeCompare(b.templateId));
  const selected = rankings.find((entry) => entry.compatible); if (!selected) return { compatible: false, templateId: null, paletteId: null, normalizedStyle: style, rankings };
  const definition = definitions.find((entry) => entry.id === selected.templateId)!;
  return { compatible: true, templateId: selected.templateId, paletteId: definition.paletteIds[0], normalizedStyle: style, rankings };
};

const templateFor = (definition: Definition): AuthoredPageTemplate<AuthoredCoverContent> => {
  const envelope: ContentEnvelope = { slots: [
    { id: "documentLabel", path: "documentLabel", kind: "text", required: true, fontFamily: "helvetica", fontStyle: "bold", fontSize: 7.5, widthMm: 80, maxLines: 1 },
    { id: "companyName", path: "companyName", kind: "text", required: true, fontFamily: definition.font, fontStyle: "bold", fontSize: definition.fontSize, widthMm: definition.nameWidth, maxLines: definition.nameLines },
    { id: "companyType", path: "companyType", kind: "text", required: true, fontFamily: "helvetica", fontStyle: "normal", fontSize: 9, widthMm: 112, maxLines: 2 },
    { id: "logo", path: "logo", kind: "image", required: false, allowedRoles: ["company_logo"], allowedProvenances: ["user_upload"] },
  ] };
  return { id: definition.id, pageRole: "cover", family: "authored_cover_library", priority: definition.priority, envelope,
    prepare: (input) => input.companyName.trim().length > definition.maxNameCharacters ? { compatible: false, instance: null, issues: [{ code: "text_line_limit_exceeded", path: "companyName", slotId: "companyName", message: `Company name exceeds the fixed ${definition.maxNameCharacters}-character authored envelope.` }] } : evaluateContentEnvelope(definition.id, envelope, input, createJsPDFMeasurementContext(new jsPDF({ unit: "mm", format: "a4" })), [input.contentId]),
    render: (pdf, instance) => { const audit: Record<string, readonly string[]> = {}; definition.render(pdf, instance, palette(instance.source.paletteId), audit); return { templateId: instance.templateId, renderedTextBySlot: audit }; },
  };
};
export const authoredCoverTemplateDefinitions = definitions.map((definition) => ({ id: definition.id, supportedFamilies: definition.supportedFamilies, styleTags: definition.styleTags, toneTags: definition.toneTags, compositionCategory: definition.compositionCategory, maxNameCharacters: definition.maxNameCharacters, supportsLogo: definition.supportsLogo, paletteIds: definition.paletteIds, priority: definition.priority, font: definition.font, fontSize: definition.fontSize, nameWidth: definition.nameWidth, nameLines: definition.nameLines }));
export const authoredCoverTemplates = definitions.map(templateFor);
export const getAuthoredCoverTemplate = (id: CoverTemplateId) => authoredCoverTemplates.find((template) => template.id === id) ?? null;
