import type { AuthoredCorpusRecord } from "./beta-corpus/fixtures";
import type { ProductionEnrichmentInput } from "./enrichment";

const PNG = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=";
const item = (label: string, index: number) => ({ name: `${label} ${index + 1}`, description: `Source-backed synthetic ${label.toLowerCase()} description ${index + 1}.` });
const base = (id: string, companyType: string, role: "services" | "features", count: number, density: "sparse" | "normal" | "dense" = "normal"): ProductionEnrichmentInput => ({
  company: { name: id, about: "Clearly labelled synthetic production-shaped company source narrative.", activities: "Clearly labelled synthetic source activities and capabilities.", experience: "Clearly labelled synthetic source operating experience." },
  profile: { companyName: id, companyType, sections: [
    { id: "about", title: `About ${id}`, description: "Source-backed company overview.", content: density === "sparse" ? "Synthetic sparse source narrative." : density === "dense" ? "Synthetic dense source narrative describing the supplied organization, its operating model, its priorities, and the practical context for its work without inventing claims or statistics." : "Synthetic normal source narrative describing the supplied organization and its work.", items: [] },
    { id: role, title: role === "features" ? "Product capabilities" : "Services", description: "Source-backed capability summary.", content: "Synthetic source capability content.", items: Array.from({ length: count }, (_, index) => item(role === "features" ? "Feature" : "Service", index)) },
  ] }, projects: [],
});
const visual = (id: string, type: string, projects: number): AuthoredCorpusRecord => { const input = base(id, type, "services", 4); input.projects = Array.from({ length: projects }, (_, index) => ({ id: `${id}:project:${index + 1}`, name: `Project ${index + 1}`, description: "Source-backed synthetic project description.", imageUrl: PNG })); input.profile.sections = [...input.profile.sections, { id: "projects", title: "Selected work", description: "Authentic uploaded work.", content: "Source-backed project presentation.", items: input.projects.map((project) => ({ name: project.name, description: project.description })) }]; return { id, description: `${type}; ${projects} projects; alternating portrait/landscape decoder coverage`, input, expectation: { acceptableModes: ["authored"], preferredFamily: "visual-portfolio", rationale: "Authentic complete project coverage." } }; };
const corporate = (id: string, type: string, services: number, density: "sparse" | "normal" | "dense" = "normal"): AuthoredCorpusRecord => ({ id, description: `${type}; ${services} services; ${density}`, input: base(id, type, "services", services, density), expectation: { acceptableModes: ["authored"], preferredFamily: "corporate-services", rationale: "Service-led project-free profile." } });
const product = (id: string, type: string, features: number, useCases: number, density: "sparse" | "normal" | "dense" = "normal"): AuthoredCorpusRecord => { const input = base(id, type, "features", features, density); if (useCases) input.profile.sections = [...input.profile.sections, { id: "useCases", title: "Use cases", description: "Source-backed applications.", content: "Synthetic use-case source content.", items: Array.from({ length: useCases }, (_, index) => item("Use Case", index)) }]; return { id, description: `${type}; ${features} features; ${useCases} use cases; ${density}`, input, expectation: { acceptableModes: ["authored"], preferredFamily: "product-tech", rationale: "Product-led project-free profile." } };
};

const ambiguous = base("Mixed Advisory Platform", "Consulting software platform", "services", 3); ambiguous.profile.sections = [...ambiguous.profile.sections, { id: "team-solutions", title: "Team solutions", description: "Ambiguous intent.", content: "Required ambiguous content.", items: [] }];

export const THREE_FAMILY_GO_LIVE_CORPUS: readonly AuthoredCorpusRecord[] = [
  visual("visual-interior-1", "Interior design studio", 1), visual("visual-architecture-2", "Architecture practice", 2), visual("visual-creative-4", "Creative agency", 4), visual("visual-real-estate-8", "Real estate development", 8), visual("visual-construction-12", "Construction design build", 12),
  corporate("corporate-consulting-1", "Management consulting", 1, "sparse"), corporate("corporate-legal-2", "Accounting and legal services", 2), corporate("corporate-healthcare-4", "Healthcare services", 4), corporate("corporate-marketing-8", "B2B marketing services", 8), corporate("corporate-sme-12", "General professional services SME", 12, "dense"),
  product("product-saas-sparse", "B2B SaaS platform", 1, 0, "sparse"), product("product-software-normal", "Software product company", 4, 0), product("product-ai-dense", "AI technology startup", 12, 9, "dense"), product("product-platform-cases", "Product-led digital platform", 6, 3),
  { id: "mixed-ambiguous-safe-fallback", description: "Intentionally ambiguous mixed consulting/platform company", input: ambiguous, expectation: { acceptableModes: ["fallback"], rationale: "Required ambiguous role must fail explicitly." } },
];
